name: my-env-k8s-nodes-scale-up

on:
  schedule:
    - cron: "0 7 * * 1-5"

jobs:
  my-env-k8s-nodes-scale-up:
    uses: ./.github/workflows/k8s-nodes-scaling.yaml
    with:
      environment: myenv.myid
      cluster_type: all
      number_nodes: 1
      k8s_nodes_scaling_stage: apply
    secrets: inherit

