name: my-env-k8s-nodes-scale-down

on:
  schedule:
    - cron: "0 18 * * 1-5"

jobs:
  my-env-k8s-nodes-scale-down:
    uses: ./.github/workflows/k8s-nodes-scaling.yaml
    with:
      environment: myenv.myid
      cluster_type: all
      number_nodes: 0
      k8s_nodes_scaling_stage: apply
    secrets: inherit
      
